name: build

on:
  push:
    branches: [main, "feature/**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilar (g++ C++17)
        run: g++ -std=c++17 -O2 -pthread -Wall -Wextra -Iinclude src/*.cpp -o streaming_platform

      - name: Verificar el binario
        run: test -x streaming_platform && echo "Build OK"
